---
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: inhibitors.kubirds.com
spec:
  group: kubirds.com
  names:
    kind: Inhibitor
    plural: inhibitors
    shortNames:
      - inhibitor
    singular: inhibitor
  scope: Namespaced
  versions:
    - name: v1
      schema:
        openAPIV3Schema:
          properties:
            spec:
              properties:
                duration:
                  minLength: 1
                  type: string
                emptySelectorBehavior:
                  enum:
                    - MatchAll
                    - MatchNone
                  type: string
                schedule:
                  minLength: 1
                  type: string
                startDate:
                  minLength: 1
                  type: string
                unitSelector:
                  additionalProperties:
                    minLength: 1
                    type: string
                  type: object
              required:
                - unitSelector
                - emptySelectorBehavior
                - schedule
                - duration
                - startDate
              type: object
          required:
            - spec
          type: object
      served: true
      storage: true
