---
apiVersion: kubirds.com/v1
kind: Unit
metadata:
  name: {{ include "kubirds-curl-unit.fullname" . }}
  labels:
    {{- include "kubirds-curl-unit.labels" . | nindent 4 }}
    {{ if .Values.labels }}
    {{ .Values.labels | toYaml | nindent 4 }}
    {{ end}}
spec:
  schedule: {{ .Values.schedule }}
  image:
    name: {{ .Values.image.name }}
    pullPolicy: {{ .Values.image.pullPolicy }}
    command: "curl -L {{ .Values.args }} $HOST"
  env:
    - name: HOST
      {{ .Values.host | toYaml | nindent 6 }}
