---
apiVersion: kubirds.com/v1
kind: Unit
metadata:
  name: {{ include "kubirds-klifter-unit.fullname" . }}
  labels:
    {{- include "kubirds-klifter-unit.labels" . | nindent 4 }}
    {{ if .Values.labels }}
    {{ .Values.labels | toYaml | nindent 4 }}
    {{ end}}
spec:
  schedule: {{ .Values.schedule }}
  image:
    name: {{ .Values.image.name }}
    pullPolicy: {{ .Values.image.pullPolicy }}
    command: "poetry run ansible-playbook site.yml"
  env:
    - name: K8S_STATE_SOURCE_KIND
      value: git
    - name: K8S_STATE_SOURCE_GIT_URL
      value: {{ .Values.git_url }}
    - name: K8S_STATE_SOURCE_GIT_REF
      value: {{ .Values.git_ref }}
    - name: K8S_STATE_SOURCE_GIT_DIR
      value: {{ .Values.git_dir }}
