---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "tlsmon.fullname" . }}-notifier-scripts
  labels:
    {{- include "tlsmon.labels" . | nindent 4 }}
data:
  tlsmon-parse-unit.sh: |
    #!/bin/sh
    set -e
    # UNIT_OUTPUT is an array of
    #     {"url": "...", "mail": "...", "msg": "..."}
    jq '.|keys[]' $UNIT_OUTPUT | while read idx
    do
      export USER_MAIL=$(jq -r ".[${idx}].mail" $UNIT_OUTPUT)
      export USER_LOCALE=$(jq -r ".[${idx}].locale" $UNIT_OUTPUT)
      export WEBSITE_ERRORS=$(jq -r ".[${idx}].errors $UNIT_OUTPUT")
      exec /usr/local/bin/sendmail
    done
