---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "tlsmon.fullname" . }}-notifier-mail-templates
  labels:
    {{- include "tlsmon.labels" . | nindent 4 }}
data:
  recipients.txt: "{{ .Env.WEBSITE_MAIL }}"
  subject.txt: "[DOWN ALERT] {{ .Env.WEBSITE_URL }}"
  body.html: |
    <p>
      <b>DownAlert</b> detected a problem with the website located at
      <pre>{{ .Env.WEBSITE_URL }}</pre>:
    </p>
    <pre style="margin-left: 3em;">{{ .Env.TLSMON_MSG }}</pre>
    <p>
      You are receiving this email because you subscribed to the
      <a href="https://downalert.com">DownAlert</a> service.
      <br/>
      If you no longer want to receive emails from us, please click
      <a href="https://downalert.com/unsubscribe">here</a> to unsubscribe.
    </p>
