{{/*
  Verify all credentials have been set.
*/}}
{{- if (not .Values.credentials.stripe.webhook) }}
{{- fail "Missing credentials 'stripe.webhook'" }}
{{- end }}

{{- if (not .Values.credentials.stripe.secret) }}
{{- fail "Missing credentials 'stripe.secret'" }}
{{- end }}

{{- if (not .Values.credentials.stripe.publishableKey) }}
{{- fail "Missing credentials 'stripe.publishableKey'" }}
{{- end }}

{{- if (not .Values.credentials.stripe.priceId) }}
{{- fail "Missing credentials 'stripe.priceId'" }}
{{- end }}

{{- if (not .Values.credentials.database.url) }}
{{- fail "Missing credentials 'database.url'" }}
{{- end }}

{{- if (not .Values.credentials.stripe.webhook) }}
{{- fail "Missing credentials 'stripe.webhook'" }}
{{- end }}

{{- if (not .Values.credentials.mailjet.apiKey) }}
{{- fail "Missing credentials 'mailjet.apiKey'" }}
{{- end }}

{{- if (not .Values.credentials.mailjet.secretKey) }}
{{- fail "Missing credentials 'mailjet.secretKey'" }}
{{- end }}

apiVersion: v1
kind: Secret
metadata:
  name: {{ include "tlsmon.fullname" . }}
  labels:
    {{- include "tlsmon.labels" . | nindent 4 }}
data:
  STRIPE_WEBHOOK_KEY: {{ .Values.credentials.stripe.webhook | b64enc | quote  }}
  STRIPE_SECRET_KEY: {{ .Values.credentials.stripe.secret | b64enc | quote  }}
  STRIPE_PUBLISHABLE_KEY: {{ .Values.credentials.stripe.publishableKey | b64enc | quote  }}
  STRIPE_PRICE_ID: {{ .Values.credentials.stripe.priceId | b64enc | quote  }}
  DJANGO_SECRET_KEY: {{ randAlphaNum 64 | b64enc | quote  }}
  TLSMON_CHECK_TOKEN: {{ randAlphaNum 64 | b64enc | quote  }}
  DATABASE_URL: {{ .Values.credentials.database.url | b64enc | quote  }}
  MAILJET_API_KEY: {{ .Values.credentials.mailjet.apiKey | b64enc | quote  }}
  MAILJET_SECRET_KEY: {{ .Values.credentials.mailjet.secretKey | b64enc | quote  }}
