apiVersion: v1
kind: Secret
metadata:
  name: {{ include "tlsmon.fullname" . }}
  labels:
    {{- include "tlsmon.labels" . | nindent 4 }}
data:
  STRIPE_WEBHOOK_KEY: {{ .Values.credentials.stripe.webhook | b64enc | quote  }}
  STRIPE_SECRET_KEY: {{ .Values.credentials.stripe.secret | b64enc | quote  }}
  STRIPE_PUBLISHABLE_KEY: {{ .Values.credentials.stripe.publishableKey | b64enc | quote  }}
  STRIPE_PRICE_ID: {{ .Values.credentials.stripe.priceId | b64enc | quote  }}
  STRIPE_FIRST100_ID: {{ .Values.credentials.stripe.first100Id | b64enc | quote  }}
  DJANGO_SECRET_KEY: {{ randAlphaNum 64 | b64enc | quote  }}
  TLSMON_CHECK_TOKEN: {{ randAlphaNum 64 | b64enc | quote  }}
  DATABASE_URL: {{ .Values.credentials.database.url | b64enc | quote  }}
  MAILJET_API_KEY: {{ .Values.credentials.mailjet.apiKey | b64enc | quote  }}
  MAILJET_SECRET_KEY: {{ .Values.credentials.mailjet.secretKey | b64enc | quote  }}
