---

credentials:
  stripe:
    webhook: null
    secret: null
    publishableKey: null
    priceId: null
  database:
    url: null
  mailjet:
    apiKey: null
    secretKey: null

replicaCount: 1

images:
  server:
    repository: linksociety/tlsmon-webserver
    pullPolicy: IfNotPresent
    tag: "1.0.0"
    pullSecrets: []

  checker:
    repository: curlimages/curl
    pullPolicy: IfNotPresent
    tag: "7.85.0"

  notifier:
    repository: linksociety/kubirds-reactor-mailjet
    pullPolicy: IfNotPresent
    tag: "0.1.1"

nameOverride: ""
fullnameOverride: ""

serviceAccount:
  create: true
  annotations: {}
  name: ""

podAnnotations: {}

podSecurityContext: {}
  # fsGroup: 2000

securityContext: {}
  # capabilities:
  #   drop:
  #   - ALL
  # readOnlyRootFilesystem: true
  # runAsNonRoot: true
  # runAsUser: 1000

service:
  type: ClusterIP
  port: 80

ingress:
  enabled: false
  className: ""
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt
  host: downalert.com

resources:
  limits:
    cpu: 10m
    memory: 128Mi
  requests:
    cpu: 10m
    memory: 128Mi

autoscaling:
  enabled: false
  minReplicas: 1
  maxReplicas: 100
  targetCPUUtilizationPercentage: 80
  # targetMemoryUtilizationPercentage: 80

nodeSelector: {}

tolerations: []

affinity: {}
