---
apiVersion: v2
description: Kubirds Helm chart
name: kubirds

type: application
version: '2.0.0'

appVersion: '2.0.0-alpha5'

dependencies:
  - name: coresup
  - name: operator
  - name: dashboard
    condition: dashboard.enabled
