---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "kubirds-operator.fullname" . }}-auth-delegator
  labels:
    {{- include "kubirds-operator.labels" . | nindent 4 }}
subjects:
  - kind: ServiceAccount
    name: {{ include "kubirds-operator.serviceAccountName" . }}
    namespace: {{ .Release.Namespace }}
roleRef:
  kind: ClusterRole
  name: system:auth-delegator
  apiGroup: rbac.authorization.k8s.io
