---
apiVersion: kubirds.com/v1
kind: Reactor
metadata:
  name: {{ include "kubirds-teams-reactor.fullname" . }}
  labels:
    {{- include "kubirds-teams-reactor.labels" . | nindent 4 }}
    {{ if .Values.labels }}
    {{ .Values.labels | toYaml | nindent 4 }}
    {{ end}}
spec:
  unitSelector:
    {{- .Values.unitSelector | toYaml | nindent 4 -}}
  image:
    name: {{ .Values.image.name }}
    pullPolicy: {{ .Values.image.pullPolicy }}
    command: {{ .Values.image.command }}
  env:
    - name: REQUEST_HEADERS
      value: |
        Content-Type: application/json
    - name: REQUEST_BODY
      value:
        {{ if eq (typeOf .Values.message) "string" }}
        { "text": "{{ .Values.message }}"}
        {{ else }}
        {{- .Values.message | toJson | nindent4 -}}
        {{ end }}
    - name: REQUEST_URL
      value: {{ .Values.webhook }}
