---
revisionHistoryLimit: 0

metadata:
  images:
    remote: git@github.com:vmware-tanzu/carvel-kapp-controller.git
    revision: 4b0307d377e429c00d8f5cf6499bf59989f71f44

image:
  repository: index.docker.io/k14s/kapp-controller@sha256
  tag: 48fd422e98ce67dbec2d2d908488816ee6cbae8abdbb7eef1f3892306219c040
  pullPolicy: IfNotPresent

controller:
  port: 10350
  createNamespace: yes
  createApiService: yes

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

serviceAccount:
  create: yes
  annotations: {}
  name: ""

rbac:
  create: yes

podAnnotations: {}

podSecurityContext:
  fsGroup: 3000

securityContext:
  runAsGroup: 2000
  runAsUser: 1000

resources:
  requests:
    cpu: 120m
    memory: 100Mi

nodeSelector: {}

tolerations: []

affinity: {}
