---
revisionHistoryLimit: 0

metadata:
  images:
    remote: git@github.com:vmware-tanzu/carvel-kapp-controller.git
    revision: a9f13d0c02645f9fb4b9699f993aa234f44f14f4

image:
  repository: index.docker.io/k14s/kapp-controller@sha256
  tag: ee05e345582e51a02249a24adf67c53f65a5fcc404bd41e74cd22704674f211f
  pullPolicy: IfNotPresent

controller:
  port: 10350
  createNamespace: yes
  createApiService: yes

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

serviceAccount:
  create: yes
  annotations: {}
  name: ""

rbac:
  create: yes

podAnnotations: {}

podSecurityContext:
  fsGroup: 3000

securityContext:
  runAsGroup: 2000
  runAsUser: 1000

resources:
  requests:
    cpu: 120m
    memory: 100Mi

nodeSelector: {}

tolerations: []

affinity: {}
