---
revisionHistoryLimit: 0

metadata:
  images:
    remote: git@github.com:vmware-tanzu/carvel-kapp-controller.git
    revision: 84fbfc9e426bfc9b4200319c38de29b0b7f82598

image:
  repository: index.docker.io/k14s/kapp-controller@sha256
  tag: 3e5e6e47c1011baccb66838904e816b0e1ce697327281b5e2d88307244af193a
  pullPolicy: IfNotPresent

controller:
  port: 10350
  createNamespace: yes

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""

serviceAccount:
  create: yes
  annotations: {}
  name: ""

rbac:
  create: yes

podAnnotations: {}

podSecurityContext:
  fsGroup: 3000

securityContext:
  runAsGroup: 2000
  runAsUser: 1000

resources:
  requests:
    cpu: 120m
    memory: 100Mi

nodeSelector: {}

tolerations: []

affinity: {}

