{{- $days := 60 -}}
{{- $caName := printf "%s-ca" (include "kubirds-operator.name" .) -}}
{{- $commonName := include "kubirds-operator.fullname" . -}}
{{- $dnsNames := list (printf "%s.%s" (include "kubirds-operator.fullname" .) .Release.Namespace) (printf "%s.%s.svc" (include "kubirds-operator.fullname" .) .Release.Namespace) -}}
{{- $ca := genCA $caName $days -}}
{{- $cert := genSignedCert $commonName nil $dnsNames $days $ca -}}
{{- $caBundle := printf "%s\n%s\n" $ca.Cert $ca.Key -}}

---
apiVersion: v1
kind: Secret
type: kubernetes.io/tls
metadata:
  name: {{ include "kubirds-operator.fullname" . }}-tls
  labels:
    {{- include "kubirds-operator.labels" . | nindent 4 }}
data:
  ca.crt: {{ $caBundle | b64enc | quote }}
  tls.crt: {{ $cert.Cert | b64enc | quote }}
  tls.key: {{ $cert.Key | b64enc | quote }}

---
apiVersion: apiregistration.k8s.io/v1
kind: APIService
metadata:
  name: {{ include "kubirds-operator.apiServiceName" . }}
  labels:
    {{- include "kubirds-operator.labels" . | nindent 4 }}
spec:
  group: {{ include "kubirds-operator.apiServiceGroup" . }}
  groupPriorityMinimum: 100
  version: {{ include "kubirds-operator.apiServiceVersion" . }}
  versionPriority: 100
  service:
    name: {{ include "kubirds-operator.fullname" . }}
    namespace: {{ .Release.Namespace }}
  caBundle: {{ $caBundle | b64enc | quote }}

---
apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  name: {{ include "kubirds-operator.fullname" . }}
  labels:
    {{- include "kubirds-operator.labels" . | nindent 4 }}
webhooks:
  - name: {{ include "kubirds-operator.admissionWebhookName" . }}
    rules:
      - apiGroups: ["kubirds.com"]
        apiVersions: ["v1"]
        operations: ["CREATE", "UPDATE"]
        resources: ["units", "reactors", "inhibitors"]
        scope: "Namespaced"
    clientConfig:
      service:
        name: {{ include "kubirds-operator.fullname" . }}
        namespace: {{ .Release.Namespace }}
        path: /webhook/validate
      caBundle: {{ $caBundle | b64enc | quote }}
    admissionReviewVersions: ["v1"]
    sideEffects: None
    timeoutSeconds: 5
