---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "kubirds-operator.fullname" . }}-operator-minimal
  labels:
    {{- include "kubirds-operator.labels" . | nindent 4 }}
rules:
  - apiGroups: ["tekton.dev"]
    resources: ["pipelines", "pipelineruns"]
    verbs: ["get", "watch", "list", "create", "update", "patch", "delete"]
  - apiGroups: ["kubirds.com"]
    resources: ["units", "reactors", "inhibitors"]
    verbs: ["get", "watch", "list", "create", "update", "patch", "delete"]
  - apiGroups: [""]
    resources: ["secrets"]
    verbs: ["create", "update", "patch", "delete"]
  - apiGroups: ["", "events.k8s.io"]
    resources: ["events"]
    verbs: ["get", "watch", "list", "create"]
  - apiGroups: [""]
    resources: ["serviceaccounts"]
    verbs: ["get"]
