apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "kubirds-operator.fullname" . }}
  labels:
    {{- include "kubirds-operator.labels" . | nindent 4 }}
spec:
  {{- if not .Values.autoscaling.enabled }}
  replicas: {{ .Values.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "kubirds-operator.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "kubirds-operator.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.image.pullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "kubirds-operator.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: main
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.name }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            - name: RELEASE_NODE_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
            - name: RELEASE_COOKIE
              valueFrom:
                secretKeyRef:
                  name: {{ include "kubirds-operator.fullname" . }}-erlcookie
                  key: "ERLANG_COOKIE"
            - name: KUBIRDS_API_SSL_KEY_PATH
              value: /etc/ssl/kubirds/tls.key
            - name: KUBIRDS_API_SSL_CERT_PATH
              value: /etc/ssl/kubirds/tls.crt
          envFrom:
            - configMapRef:
                name: {{ include "kubirds-operator.fullname" . }}
          volumeMounts:
            - name: tls-certs
              readOnly: yes
              mountPath: /etc/ssl/kubirds
          ports:
            - name: https
              containerPort: 5001
              protocol: TCP
            - name: cachelog
              containerPort: 6379
              protocol: TCP
            - name: epmd
              containerPort: 4369
              protocol: TCP
          readinessProbe:
            httpGet:
              scheme: HTTPS
              path: /health
              port: https
            initialDelaySeconds: 30
            periodSeconds: 10
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      volumes:
        - name: tls-certs
          secret:
            secretName: {{ include "kubirds-operator.fullname" . }}-tls
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
