apiVersion: v1
kind: Service
metadata:
  name: {{ include "kubirds-operator.fullname" . }}
  labels:
    {{- include "kubirds-operator.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  ports:
    - port: 443
      targetPort: https
      protocol: TCP
      name: https
    - port: 6379
      targetPort: cachelog
      protocol: TCP
      name: cachelog
  selector:
    {{- include "kubirds-operator.selectorLabels" . | nindent 4 }}
