apiVersion: v1
kind: Service
metadata:
  name: {{ include "kubirds-operator.fullname" . }}-headless
  labels:
    {{- include "kubirds-operator.labels" . | nindent 4 }}
spec:
  type: ClusterIP
  clusterIP: None
  ports:
    - port: 4369
      targetPort: epmd
      protocol: TCP
      name: epmd
  selector:
    {{- include "kubirds-operator.selectorLabels" . | nindent 4 }}
