---
apiVersion: kubirds.com/v1
kind: Reactor
metadata:
  name: {{ include "kubirds-klander-reactor.fullname" . }}
  labels:
    {{- include "kubirds-klander-reactor.labels" . | nindent 4 }}
    {{ if .Values.labels }}
    {{ .Values.labels | toYaml | nindent 4 }}
    {{ end}}
spec:
  unitSelector:
    {{ if .Values.unitSelector }}
    {{ .Values.unitSelector | toYaml | nindent 4 }}
    {{ end}}
  image:
    name: {{ .Values.image.name }}
    pullPolicy: {{ .Values.image.pullPolicy }}
    command: "klander"
  triggers:
    success: {{ .Values.triggers.success }}
    failure: {{ .Values.triggers.failure }}
    fixed: {{ .Values.triggers.fixed }}
    regression: {{ .Values.triggers.regression }}
