---
apiVersion: apiregistration.k8s.io/v1
kind: APIService
metadata:
  name: v1.api.kubirds.com
  labels:
    helm.sh/chart: {{ include "kubirds.chart" . }}
    app.kubernetes.io/name: {{ include "kubirds.name" . }}-aggregated-api
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/part-of: kubirds
spec:
  group: api.kubirds.com
  groupPriorityMinimum: 100
  version: v1
  versionPriority: 100
  service:
    name: {{ include "kubirds.fullname" . }}
    namespace: {{ .Release.Namespace }}
  caBundle: {{ .Values.tls.caBundle }}
