---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "kubirds.fullname" . }}-operator-minimal
rules:
  - apiGroups: ["tekton.dev"]
    resources: ["pipelines", "pipelineruns"]
    verbs: ["get", "watch", "list", "create", "update", "patch", "delete"]
  - apiGroups: ["kubirds.com"]
    resources: ["units", "reactors", "inhibitors"]
    verbs: ["get", "watch", "list", "create", "update", "patch", "delete"]
