---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "kubirds.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    helm.sh/chart: {{ template "kubirds.chart" . }}
    app.kubernetes.io/name: {{ template "kubirds.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/part-of: kubirds
data:
  KUBIRDS_SERVICE_NAME: "{{ include "kubirds.fullname" . }}-headless"
  KUBIRDS_STATUS_IMAGE_NAME: "{{ .Values.statusImage.name }}:{{ .Values.statusImage.tag }}"
  KUBIRDS_STATUS_IMAGE_PULL_POLICY: {{ .Values.statusImage.pullPolicy }}
  KUBIRDS_REDIS_IMAGE_NAME: "{{ .Values.redis.image.name }}:{{ .Values.redis.image.tag }}"
  KUBIRDS_REDIS_IMAGE_PULL_POLICY: "{{ .Values.redis.image.pullPolicy }}"
  KUBIRDS_REDIS_SECRET_NAME: "{{ include "kubirds.fullname" . }}-redis"
  KUBIRDS_SERVICEACCOUNT: "{{ .Values.pipelineServiceAccount }}"
