---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "kubirds.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    helm.sh/chart: {{ template "kubirds.chart" . }}
    app.kubernetes.io/name: {{ template "kubirds.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/part-of: kubirds
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app.kubernetes.io/name: {{ include "kubirds.name" . }}
      app.kubernetes.io/instance: {{ .Release.Name }}
  template:
    metadata:
      labels:
        app.kubernetes.io/name: {{ include "kubirds.name" . }}
        app.kubernetes.io/instance: {{ .Release.Name }}
    spec:
      serviceAccountName: {{ include "kubirds.fullname" . }}
      {{- with .Values.image.pullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: main
          image: "{{ .Values.image.name }}:{{ .Values.image.tag }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            - name: KUBIRDS_REDIS_HOST
            {{ if eq "static" .Values.redis.host.kind }}
              {{ .Values.redis.host.static | toYaml | nindent 14 }}
            {{ else }}
              {{ .Values.redis.host.dynamic | toYaml | nindent 14 }}
            {{ end }}
            - name: RELEASE_NODE_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
            - name: RELEASE_COOKIE
            {{ if eq "static" .Values.erlangCookie.kind }}
              {{ .Values.erlangCookie.static | toYaml | nindent 14 }}
            {{ else }}
              {{ .Values.erlangCookie.dynamic | toYaml | nindent 14 }}
            {{ end }}
            - name: KUBIRDS_API_SSL_KEY_PATH
              value: /etc/ssl/kubirds/tls.key
            - name: KUBIRDS_API_SSL_CERT_PATH
              value: /etc/ssl/kubirds/tls.crt
          envFrom:
            - configMapRef:
                name: {{ include "kubirds.fullname" . }}
          volumeMounts:
            - name: tls-certs
              readOnly: yes
              mountPath: /etc/ssl/kubirds
          ports:
            - name: https
              containerPort: 5001
              protocol: TCP
            - name: epmd
              containerPort: 4369
              protocol: TCP
          readinessProbe:
            httpGet:
              scheme: HTTPS
              path: /health
              port: https
            initialDelaySeconds: 30
            periodSeconds: 10
      volumes:
        - name: tls-certs
          secret:
            secretName: {{ .Values.tls.secretName }}
