{{- if .Values.ingress.enabled -}}
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "kubirds.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    helm.sh/chart: {{ template "kubirds.chart" . }}
    app.kubernetes.io/name: {{ template "kubirds.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/part-of: kubirds
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/rewrite-target: /$1
    nginx.ingress.kubernetes.io/configuration-snippet: |
      if ($request_uri ~ "^/controller/(.*)$") {
        add_header Cache-Control "no-cache,no-store";
      }
    {{ if .Values.ingress.annotations }}
    {{ .Values.ingress.annotations | toYaml | nindent 4 }}
    {{ end}}
spec:
  tls:
    - hosts:
        - {{ .Values.ingress.host }}
      secretName: {{ include "kubirds.fullname" . }}-tls
  rules:
    - host: {{ .Values.ingress.host }}
      http:
        paths:
{{ if .Values.controller.enabled }}
          - path: /controller/(.*)
            pathType: Prefix
            backend:
              service:
                name: {{ include "kubirds.fullname" . }}-controller
                port:
                  number: 80
{{ end }}
{{ if .Values.dashboard.enabled }}
          - path: /?(.*)
            pathType: Prefix
            backend:
              service:
                name: {{ include "kubirds.fullname" . }}-dashboard
                port:
                  number: 80
{{ end }}
{{- end -}}
