{{- if .Values.ingress.enabled -}}
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "kubirds.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    helm.sh/chart: {{ template "kubirds.chart" . }}
    app.kubernetes.io/name: {{ template "kubirds.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/part-of: kubirds
  {{ if .Values.ingress.annotations }}
  annotations:
    {{ .Values.ingress.annotations | toYaml | nindent 4 }}
  {{ end}}
spec:
  tls:
    - hosts:
        - {{ .Values.ingress.host }}
      secretName: {{ include "kubirds.fullname" . }}-tls
  rules:
    - host: {{ .Values.ingress.host }}
      http:
        paths:
          - path: /
            backend:
              service:
                name: {{ include "kubirds.fullname" . }}
                port:
                  number: 80
{{- end -}}
