---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "kubirds.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    helm.sh/chart: {{ template "kubirds.chart" . }}
    app.kubernetes.io/name: {{ template "kubirds.name" . }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/part-of: kubirds
