{{- if .Values.controller.enabled -}}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "kubirds.fullname" . }}-controller
  namespace: {{ .Release.Namespace }}
  labels:
    helm.sh/chart: {{ include "kubirds.chart" . }}
    app.kubernetes.io/name: {{ include "kubirds.name" . }}-controller
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/part-of: kubirds
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app.kubernetes.io/name: {{ include "kubirds.name" . }}-controller
    app.kubernetes.io/instance: {{ .Release.Name }}
{{- end -}}
