---
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "kubirds-operator.fullname" . }}
  labels:
    {{- include "kubirds-operator.labels" . | nindent 4 }}
data:
  KUBIRDS_HEADLESS_SERVICE_NAME: "{{ include "kubirds-operator.fullname" . }}-headless"
  KUBIRDS_SERVICE_NAME: "{{ include "kubirds-operator.fullname" . }}"
  KUBIRDS_SERVICE_NAMESPACE: "{{ .Release.Namespace }}"

  KUBIRDS_STATUS_IMAGE_NAME: "{{ .Values.statusImage.name }}:{{ .Values.statusImage.tag }}"
  KUBIRDS_STATUS_IMAGE_PULL_POLICY: {{ .Values.statusImage.pullPolicy }}

  KUBIRDS_CACHELOG_IMAGE_NAME: "{{ .Values.cachelogImage.name }}:{{ .Values.cachelogImage.tag }}"
  KUBIRDS_CACHELOG_IMAGE_PULL_POLICY: "{{ .Values.cachelogImage.pullPolicy }}"
