---
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "kubirds-operator.fullname" . }}-erlcookie
  labels:
    {{- include "kubirds-operator.labels" . | nindent 4 }}
data:
  {{- $secretName := printf "%s-erlcookie" (include "kubirds-operator.fullname" .) }}
  {{- $secret := (lookup "v1" "Secret" .Release.Namespace $secretName) | default (dict "Data" dict) }}
  {{- $cookie := (get $secret.Data "ERLANG_COOKIE" | b64dec) | default (randAlphaNum 128) }}
  ERLANG_COOKIE: {{ $cookie | b64enc | quote }}
