---
apiVersion: apiextensions.k8s.io/v1beta1
kind: CustomResourceDefinition
metadata:
  name: units.kubirds.com
spec:
  group: kubirds.com
  names:
    kind: Unit
    plural: units
    shortNames:
      - u
    singular: unit
  scope: Namespaced
  validation:
    openAPIV3Schema:
      properties:
        spec:
          properties:
            env:
              items:
                properties:
                  name:
                    minLength: 1
                    type: string
                  value:
                    type: string
                  valueFrom:
                    properties:
                      configMapKeyRef:
                        properties:
                          key:
                            minLength: 1
                            type: string
                          name:
                            minLength: 1
                            type: string
                          optional:
                            type: boolean
                        required:
                          - name
                          - key
                        type: object
                      secretKeyRef:
                        properties:
                          key:
                            minLength: 1
                            type: string
                          name:
                            minLength: 1
                            type: string
                          optional:
                            type: boolean
                        required:
                          - name
                          - key
                        type: object
                    type: object
                required:
                  - name
                type: object
              type: array
            envFrom:
              items:
                properties:
                  configMapRef:
                    properties:
                      name:
                        minLength: 1
                        type: string
                      optional:
                        type: boolean
                    required:
                      - name
                    type: object
                  prefix:
                    minLength: 1
                    type: string
                  secretRef:
                    properties:
                      name:
                        minLength: 1
                        type: string
                      optional:
                        type: boolean
                    required:
                      - name
                    type: object
                type: object
              type: array
            image:
              properties:
                command:
                  minLength: 1
                  type: string
                name:
                  minLength: 1
                  type: string
                pullPolicy:
                  enum:
                    - IfNotPresent
                    - Always
                    - Never
                  type: string
              required:
                - name
                - command
              type: object
            schedule:
              minLength: 1
              type: string
            volumes:
              items:
                properties:
                  mountPath:
                    minLength: 1
                    type: string
                  name:
                    minLength: 1
                    type: string
                required:
                  - name
                  - mountPath
                type: object
                x-kubernetes-preserve-unknown-fields: true
              type: array
          required:
            - image
            - schedule
          type: object
        status:
          properties:
            lastState:
              type: string
            lastStateSeen:
              type: string
          type: object
      required:
        - spec
      type: object
  version: v1
