---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  labels:
    {{- include "rabbitmq-cluster-operator.labels" . | nindent 4 }}
  name: {{ include "rabbitmq-cluster-operator.fullname" . }}-leader-election
  namespace: {{ .Release.Namespace }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ include "rabbitmq-cluster-operator.fullname" . }}-leader-election
subjects:
- kind: ServiceAccount
  name: {{ include "rabbitmq-cluster-operator.fullname" . }}
  namespace: {{ .Release.Namespace }}
