---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  labels:
    {{- include "rabbitmq-cluster-operator.labels" . | nindent 4 }}
  name: {{ include "rabbitmq-cluster-operator.fullname" . }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "rabbitmq-cluster-operator.fullname" . }}
subjects:
- kind: ServiceAccount
  name: {{ include "rabbitmq-cluster-operator.fullname" . }}
  namespace: {{ .Release.Namespace }}
