---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "rabbitmq-cluster-operator.fullname" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "rabbitmq-cluster-operator.labels" . | nindent 4 }}
